//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class DayWeather
    {
        public string CodWeatherCondition { get; set; }
        public int IdPosPlanet1 { get; set; }
        public int IdPosPlanet2 { get; set; }
        public int IdPosPlanet3 { get; set; }
        public double Perimeter { get; set; }
    }
}
