//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class Planet
    {
        public Planet()
        {
            this.PosPlanet = new HashSet<PosPlanet>();
        }
    
        public int IdPlanet { get; set; }
        public int Radio { get; set; }
        public int AngularVelocity { get; set; }
        public string Name { get; set; }
    
        public virtual ICollection<PosPlanet> PosPlanet { get; set; }
    }
}
