//------------------------------------------------------------------------------
// <auto-generated>
//    Este código se generó a partir de una plantilla.
//
//    Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//    Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebAPI
{
    using System;
    using System.Collections.Generic;
    
    public partial class PosPlanet
    {
        public int IdPosPlanet { get; set; }
        public int IdPlanet { get; set; }
        public int DayP { get; set; }
        public Nullable<double> PosX { get; set; }
        public Nullable<double> PosY { get; set; }
    
        public virtual Planet Planet { get; set; }
    }
}
